# Site settings
title: "The Attention Span"
description: "AI, pensiero scientifico e creativo"
baseurl: ""
url: "https://silviavicentini.github.io"
lang: it

hero:
  role: ""
  name: "Pensieri <br> sull'intelligenza artificiale  <br> e tutto ciò che cambia il modo di pensare."
  tagline: "Quello che cattura la mia attenzione, scritto come posso."

author:
  name: Silvia Vicentini
  email: ""
  github: https://github.com/silviavicentini
permalink: /:categories/:title/

# Navigation
navigation:
  - name: Home
    url: /
  - name: Posts
    url: /posts
  - name: About
    url: /about

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

collections:
  pages:
    output: true
    permalink: /:name/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - context
